[platformio]
; 核心镜像源（关键）
extra_configs =
    https://ghproxy.com/https://raw.githubusercontent.com/platformio/platformio-core/master/platformio/assets/mirrors.json

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 921600
upload_speed = 921600

; 分区表 - 需要包含 SPIFFS
board_build.partitions = default.csv

; 库依赖
lib_deps =
    ; 无需额外库，使用 Arduino 内置 WiFi/WebServer/SPIFFS/mDNS

; 编译选项
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DARDUINO_USB_CDC_ON_BOOT=0
